// <auto-generated />
using System;
using Finance.Infra.EF.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finance.Infra.EF.Migrations
{
    [DbContext(typeof(FinanceContext))]
    [Migration("20240311112449_LoanAccountNumberIsNullable")]
    partial class LoanAccountNumberIsNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Finance.Domain.AccountContext.Aggregates.OwnerAggregate.Entities.AccountOwner", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("AccountOwner", "AccountContext");
                });

            modelBuilder.Entity("Finance.Domain.BankingContext.Aggregates.AccountAggregate.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountOwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CloseReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Closed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountOwnerId");

                    b.ToTable("Account", "AccountContext");
                });

            modelBuilder.Entity("Finance.Domain.BankingContext.Aggregates.AccountAggregate.Entities.AccountTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountTransaction", "AccountContext");
                });

            modelBuilder.Entity("Finance.Domain.CustomerContext.Aggregates.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer", "CustomerContext");
                });

            modelBuilder.Entity("Finance.Domain.LoanContext.Aggregates.LoanAggregate.Entities.Loan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("BankRate")
                        .HasColumnType("float");

                    b.Property<bool>("Closed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoanAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanCustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoanCustomerId");

                    b.ToTable("Loan", "LoanContext");
                });

            modelBuilder.Entity("Finance.Domain.LoanContext.Aggregates.LoanAggregate.Entities.LoanApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<double>("BankRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoadCustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LoanApplication", "LoanContext");
                });

            modelBuilder.Entity("Finance.Domain.LoanContext.Aggregates.LoanAggregate.Entities.LoanCustomer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CreditScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LoanCustomer", "LoanContext");
                });

            modelBuilder.Entity("Finance.Domain.LoanContext.Aggregates.LoanAggregate.Entities.LoanDebt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoanId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanDebt", "LoanContext");
                });

            modelBuilder.Entity("Finance.Domain.AccountContext.Aggregates.OwnerAggregate.Entities.AccountOwner", b =>
                {
                    b.OwnsOne("Finance.Domain.AccountContext.Aggregates.AccountAggregate.Enumarations.AccountType", "AccountType", b1 =>
                        {
                            b1.Property<string>("AccountOwnerId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("Account_Type_Code");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AccountOwnerId");

                            b1.ToTable("AccountOwner", "AccountContext");

                            b1.WithOwner()
                                .HasForeignKey("AccountOwnerId");
                        });

                    b.Navigation("AccountType")
                        .IsRequired();
                });

            modelBuilder.Entity("Finance.Domain.BankingContext.Aggregates.AccountAggregate.Entities.Account", b =>
                {
                    b.HasOne("Finance.Domain.AccountContext.Aggregates.OwnerAggregate.Entities.AccountOwner", null)
                        .WithMany("Accounts")
                        .HasForeignKey("AccountOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Finance.Domain.Shared.ValueObjects.Money", "Balance", b1 =>
                        {
                            b1.Property<string>("AccountId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Balance_Currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Balance_Amount");

                            b1.HasKey("AccountId");

                            b1.ToTable("Account", "AccountContext");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("Balance")
                        .IsRequired();
                });

            modelBuilder.Entity("Finance.Domain.BankingContext.Aggregates.AccountAggregate.Entities.AccountTransaction", b =>
                {
                    b.HasOne("Finance.Domain.BankingContext.Aggregates.AccountAggregate.Entities.Account", null)
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Finance.Domain.Shared.ValueObjects.Money", "Money", b1 =>
                        {
                            b1.Property<string>("AccountTransactionId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Money_Currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Money_Amount");

                            b1.HasKey("AccountTransactionId");

                            b1.ToTable("AccountTransaction", "AccountContext");

                            b1.WithOwner()
                                .HasForeignKey("AccountTransactionId");
                        });

                    b.OwnsOne("Finance.Domain.BankingContext.Aggregates.AccountAggregate.Enumarations.AccountTransactionType", "Type", b1 =>
                        {
                            b1.Property<string>("AccountTransactionId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("Transaction_Code");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AccountTransactionId");

                            b1.ToTable("AccountTransaction", "AccountContext");

                            b1.WithOwner()
                                .HasForeignKey("AccountTransactionId");
                        });

                    b.OwnsOne("Finance.Domain.BankingContext.Aggregates.AccountAggregate.Enumarations.MoneyTransferChannel", "TransferChannel", b1 =>
                        {
                            b1.Property<string>("AccountTransactionId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("Transafer_Channel_Code");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AccountTransactionId");

                            b1.ToTable("AccountTransaction", "AccountContext");

                            b1.WithOwner()
                                .HasForeignKey("AccountTransactionId");
                        });

                    b.Navigation("Money")
                        .IsRequired();

                    b.Navigation("TransferChannel")
                        .IsRequired();

                    b.Navigation("Type")
                        .IsRequired();
                });

            modelBuilder.Entity("Finance.Domain.LoanContext.Aggregates.LoanAggregate.Entities.Loan", b =>
                {
                    b.HasOne("Finance.Domain.LoanContext.Aggregates.LoanAggregate.Entities.LoanCustomer", null)
                        .WithMany("Loans")
                        .HasForeignKey("LoanCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Finance.Domain.Shared.ValueObjects.Money", "PrincipalAmount", b1 =>
                        {
                            b1.Property<string>("LoanId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Principle_Currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Principle_Amount");

                            b1.HasKey("LoanId");

                            b1.ToTable("Loan", "LoanContext");

                            b1.WithOwner()
                                .HasForeignKey("LoanId");
                        });

                    b.OwnsOne("Finance.Domain.Shared.ValueObjects.Money", "RemainingAmount", b1 =>
                        {
                            b1.Property<string>("LoanId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Remaning_Currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Remaning_Amount");

                            b1.HasKey("LoanId");

                            b1.ToTable("Loan", "LoanContext");

                            b1.WithOwner()
                                .HasForeignKey("LoanId");
                        });

                    b.Navigation("PrincipalAmount")
                        .IsRequired();

                    b.Navigation("RemainingAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("Finance.Domain.LoanContext.Aggregates.LoanAggregate.Entities.LoanApplication", b =>
                {
                    b.OwnsOne("Finance.Domain.Shared.ValueObjects.Money", "AnnualIncome", b1 =>
                        {
                            b1.Property<string>("LoanApplicationId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AnnoulIncome_Currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AnnoulIncome_Amount");

                            b1.HasKey("LoanApplicationId");

                            b1.ToTable("LoanApplication", "LoanContext");

                            b1.WithOwner()
                                .HasForeignKey("LoanApplicationId");
                        });

                    b.OwnsOne("Finance.Domain.Shared.ValueObjects.Money", "LoanAmount", b1 =>
                        {
                            b1.Property<string>("LoanApplicationId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Loan_Currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Loan_Amount");

                            b1.HasKey("LoanApplicationId");

                            b1.ToTable("LoanApplication", "LoanContext");

                            b1.WithOwner()
                                .HasForeignKey("LoanApplicationId");
                        });

                    b.OwnsOne("Finance.Domain.LoanContext.Aggregates.LoanAggregate.Enumerations.LoanApplicationType", "LoanType", b1 =>
                        {
                            b1.Property<string>("LoanApplicationId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("Loan_Type");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("LoanApplicationId");

                            b1.ToTable("LoanApplication", "LoanContext");

                            b1.WithOwner()
                                .HasForeignKey("LoanApplicationId");
                        });

                    b.Navigation("AnnualIncome")
                        .IsRequired();

                    b.Navigation("LoanAmount")
                        .IsRequired();

                    b.Navigation("LoanType")
                        .IsRequired();
                });

            modelBuilder.Entity("Finance.Domain.LoanContext.Aggregates.LoanAggregate.Entities.LoanCustomer", b =>
                {
                    b.OwnsOne("Finance.Domain.Shared.ValueObjects.Money", "AnnualIncome", b1 =>
                        {
                            b1.Property<string>("LoanCustomerId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AnnualIncome_Currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AnnualIncome_Amount");

                            b1.HasKey("LoanCustomerId");

                            b1.ToTable("LoanCustomer", "LoanContext");

                            b1.WithOwner()
                                .HasForeignKey("LoanCustomerId");
                        });

                    b.Navigation("AnnualIncome")
                        .IsRequired();
                });

            modelBuilder.Entity("Finance.Domain.LoanContext.Aggregates.LoanAggregate.Entities.LoanDebt", b =>
                {
                    b.HasOne("Finance.Domain.LoanContext.Aggregates.LoanAggregate.Entities.Loan", null)
                        .WithMany("Debts")
                        .HasForeignKey("LoanId");

                    b.OwnsOne("Finance.Domain.Shared.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<string>("LoanDebtId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Debt_Currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Debt_Amount");

                            b1.HasKey("LoanDebtId");

                            b1.ToTable("LoanDebt", "LoanContext");

                            b1.WithOwner()
                                .HasForeignKey("LoanDebtId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("Finance.Domain.AccountContext.Aggregates.OwnerAggregate.Entities.AccountOwner", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Finance.Domain.BankingContext.Aggregates.AccountAggregate.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Finance.Domain.LoanContext.Aggregates.LoanAggregate.Entities.Loan", b =>
                {
                    b.Navigation("Debts");
                });

            modelBuilder.Entity("Finance.Domain.LoanContext.Aggregates.LoanAggregate.Entities.LoanCustomer", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
